services:
  api:
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:root@db:5432/TodoDatabase
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - api-network

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: TodoDatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - api-network
    ports:
      - "5432:5432"

volumes:
  pgdata:

networks:
  api-network:
